version: '3.7'
services:

    redis:
        image: 'redis:latest'
    
    postgres:
        image: 'postgres:latest'
        environment: 
            - POSTGRES_HOST_AUTH_METHOD=trust

    web:
        container_name: sayollo_backend
        build:
            dockerfile: Dockerfile.dev
            context: .
        volumes:
            - .:/app/
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGHOST=postgres
            - PGUSER=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres
            - PGPORT=5432
        depends_on: 
            - postgres
            - redis
